"""Game content schemas — Pydantic models for game types and content items."""

from enum import Enum
from pydantic import BaseModel, Field


class GameType(str, Enum):
    """Supported game types for content generation."""

    QUIZ = "quiz"
    FLASHCARD = "flashcard"
    FILL_BLANK = "fill_blank"
    # Phase 2+
    # ADVENTURE = "adventure"
    # MATCHING = "matching"
    # TRUE_FALSE = "true_false"
    # ORDERING = "ordering"


class DifficultyLevel(str, Enum):
    """Cognitive difficulty levels aligned with Vietnamese THPT standards.

    Based on Thong tu 22/2021/TT-BGDDT and national exam matrices (ma tran de thi):
    - RECALL (Nhan biet): Knowledge recall, recognition, identification (~30-40%)
    - COMPREHENSION (Thong hieu): Understanding, explanation, interpretation (~30%)
    - APPLICATION (Van dung): Apply procedures to routine problems (~20-30%)
    - HIGH_APPLICATION (Van dung cao): Non-routine, multi-step, synthesis (~10%)
    """

    RECALL = "recall"
    COMPREHENSION = "comprehension"
    APPLICATION = "application"
    HIGH_APPLICATION = "high_application"


class ContentItem(BaseModel):
    """Base educational content — Q&A at its core.

    Generated by Content Agent, transformed by Formatter into game-specific output.
    """

    question: str = Field(..., description="The question or prompt")
    answer: str = Field(..., description="The correct answer")
    explanation: str = Field(
        ..., description="Explanation of why the answer is correct"
    )
    topic: str = Field(
        ..., description="Subject topic (e.g., 'Derivatives', 'Newton's Laws')"
    )
    difficulty: DifficultyLevel = Field(default=DifficultyLevel.COMPREHENSION)
    context_source: str = Field(..., description="Source document/page reference")
    doc_scope: str = Field(..., description="Origin: 'system' or 'user'")
    computation_trace: str | None = Field(
        default=None, description="Code execution trace for math problems"
    )


# --- Quiz ---
class QuizOption(BaseModel):
    """A single option in a multiple-choice quiz question."""

    text: str
    is_correct: bool = False


class QuizQuestion(BaseModel):
    """Multiple-choice quiz question with 4 options."""

    id: str
    question: str
    options: list[QuizOption] = Field(..., min_length=4, max_length=4)
    correct_answer_index: int = Field(..., ge=0, le=3)
    explanation: str
    difficulty: DifficultyLevel
    topic: str
    computation_trace: str | None = None


# --- Flashcard ---
class Flashcard(BaseModel):
    """Two-sided flashcard for memorization."""

    id: str
    front: str = Field(..., description="Concept / formula / question")
    back: str = Field(..., description="Explanation + example")
    topic: str
    difficulty: DifficultyLevel
    tags: list[str] = Field(default_factory=list)


# --- Fill-in-blank ---
class BlankSlot(BaseModel):
    """A blank slot in a fill-in-the-blank question."""

    position: int = Field(..., description="Position of blank in template (0-indexed)")
    correct_answer: str
    hint: str | None = None


class FillBlankQuestion(BaseModel):
    """Fill-in-the-blank question with one or more blanks."""

    id: str
    template: str = Field(
        ..., description="Template with blanks, e.g., 'Fe + __ HCl → ...'"
    )
    blanks: list[BlankSlot] = Field(..., min_length=1)
    explanation: str
    difficulty: DifficultyLevel
    topic: str


# --- Typed content map (replaces dict[str, list[dict]]) ---
class GameContentMap(BaseModel):
    """Typed content map — one list per game type.

    Rule: NEVER use untyped dicts (dict[str, list[dict]]) for API payloads.
    Every field must be explicitly typed so client codegen and validation work.
    """

    quiz: list[QuizQuestion] = Field(default_factory=list)
    flashcard: list[Flashcard] = Field(default_factory=list)
    fill_blank: list[FillBlankQuestion] = Field(default_factory=list)
